
package telasgraficas;

/**
 *
 * @author aluno
 */


public class jfIniciaServidor extends javax.swing.JFrame {

    /**
     * Creates new form jfIniciaServidor
     */
    public jfIniciaServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpIniciaServidor = new javax.swing.JPanel();
        jlTalkChat = new javax.swing.JLabel();
        jlServidorIniciado = new javax.swing.JLabel();
        jbVoltaTelaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTalkChat.setFont(new java.awt.Font("Abyssinica SIL", 1, 36)); // NOI18N
        jlTalkChat.setText("TalkChat");

        jlServidorIniciado.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jlServidorIniciado.setText("Servidor iniciado com sucesso!");

        jbVoltaTelaInicial.setText("Ok");
        jbVoltaTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltaTelaInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIniciaServidorLayout = new javax.swing.GroupLayout(jpIniciaServidor);
        jpIniciaServidor.setLayout(jpIniciaServidorLayout);
        jpIniciaServidorLayout.setHorizontalGroup(
            jpIniciaServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIniciaServidorLayout.createSequentialGroup()
                .addGroup(jpIniciaServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIniciaServidorLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jlTalkChat))
                    .addGroup(jpIniciaServidorLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jlServidorIniciado)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIniciaServidorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbVoltaTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        jpIniciaServidorLayout.setVerticalGroup(
            jpIniciaServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIniciaServidorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlTalkChat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jlServidorIniciado)
                .addGap(18, 18, 18)
                .addComponent(jbVoltaTelaInicial)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jlServidorIniciado.getAccessibleContext().setAccessibleName("jlServidorInciado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpIniciaServidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpIniciaServidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltaTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltaTelaInicialActionPerformed
        this.setVisible(false);
        jfTelaInicial jfTelaInicial = new jfTelaInicial();
        jfTelaInicial.setVisible(true);
    }//GEN-LAST:event_jbVoltaTelaInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfIniciaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfIniciaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfIniciaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfIniciaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfIniciaServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbVoltaTelaInicial;
    private javax.swing.JLabel jlServidorIniciado;
    private javax.swing.JLabel jlTalkChat;
    private javax.swing.JPanel jpIniciaServidor;
    // End of variables declaration//GEN-END:variables
}
