package telasgraficas;

import cliente.Usuario;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import modelos.Mensagem;

import servidor.Servidor;

/**
 *
 * @author aluno
 */
public class jfTalkChat extends javax.swing.JFrame {

    DefaultListModel listaDeUsuariosOnline = new DefaultListModel();
    Usuario usuario = Usuario.getInstance();
    Servidor servidor = Servidor.getInstance();
    ArrayList<String> arrayUsuariosOnline = new ArrayList<>();
    String destinatario = null;

    /**
     * Creates new form jfTalkChat
     */
    public jfTalkChat() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTalkChat = new javax.swing.JPanel();
        jlTalkChat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaUsuariosOnline = new javax.swing.JList<>();
        jbAtualizaListaDeUsuariosOn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtpMostraMensagens = new javax.swing.JTextPane();
        jbEnviar = new javax.swing.JButton();
        jtCaixaDeTexto = new javax.swing.JTextField();
        jbVoltaTelaInicial = new javax.swing.JButton();
        jlNomeDestinatario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTalkChat.setFont(new java.awt.Font("Abyssinica SIL", 1, 36)); // NOI18N
        jlTalkChat.setText("TalkChat");

        jLabel1.setText("Usuários Online");

        jScrollPane1.setViewportView(jListaUsuariosOnline);

        jbAtualizaListaDeUsuariosOn.setText("Atualizar");
        jbAtualizaListaDeUsuariosOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizaListaDeUsuariosOnActionPerformed(evt);
            }
        });

        jtpMostraMensagens.setEditable(false);
        jScrollPane2.setViewportView(jtpMostraMensagens);

        jbEnviar.setText("Enviar");
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });

        jtCaixaDeTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCaixaDeTextoActionPerformed(evt);
            }
        });

        jbVoltaTelaInicial.setText("Sair");
        jbVoltaTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltaTelaInicialActionPerformed(evt);
            }
        });

        jlNomeDestinatario.setText("Conversas");

        javax.swing.GroupLayout jpTalkChatLayout = new javax.swing.GroupLayout(jpTalkChat);
        jpTalkChat.setLayout(jpTalkChatLayout);
        jpTalkChatLayout.setHorizontalGroup(
            jpTalkChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTalkChatLayout.createSequentialGroup()
                .addGroup(jpTalkChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTalkChatLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jbAtualizaListaDeUsuariosOn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbEnviar)
                        .addGap(1, 1, 1)
                        .addComponent(jbVoltaTelaInicial))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTalkChatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jpTalkChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtCaixaDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpTalkChatLayout.createSequentialGroup()
                        .addGroup(jpTalkChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTalkChatLayout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(jlTalkChat))
                            .addGroup(jpTalkChatLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(jlNomeDestinatario)))
                        .addGap(0, 248, Short.MAX_VALUE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jpTalkChatLayout.setVerticalGroup(
            jpTalkChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTalkChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTalkChat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTalkChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlNomeDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTalkChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(jpTalkChatLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCaixaDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTalkChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAtualizaListaDeUsuariosOn)
                    .addComponent(jbEnviar)
                    .addComponent(jbVoltaTelaInicial))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpTalkChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTalkChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void pegaValorDoList() {
        this.destinatario = jListaUsuariosOnline.getSelectedValuesList().toString();

    }

    private void jbAtualizaListaDeUsuariosOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizaListaDeUsuariosOnActionPerformed

        try {
            arrayUsuariosOnline = this.servidor.atualizaListaUsuariosOnline();
            for (String us : arrayUsuariosOnline) {
                listaDeUsuariosOnline.addElement(us);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(jfTalkChat.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.jListaUsuariosOnline.setModel(listaDeUsuariosOnline);
    }//GEN-LAST:event_jbAtualizaListaDeUsuariosOnActionPerformed

    private void jbVoltaTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltaTelaInicialActionPerformed
        this.setVisible(false);
        jfTelaInicial jfTelaInicial = new jfTelaInicial();
        jfTelaInicial.setVisible(true);
    }//GEN-LAST:event_jbVoltaTelaInicialActionPerformed

    private void jtCaixaDeTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCaixaDeTextoActionPerformed
        
    }//GEN-LAST:event_jtCaixaDeTextoActionPerformed

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
        pegaValorDoList();
        while (true) {
            try {
                Mensagem mensagemInterface = new Mensagem();
                mensagemInterface.setDestinatario(destinatario);
                mensagemInterface.setConteudoMensagem(getCaixaDeTexto());
                usuario.enviaMensagemLocal(mensagemInterface);
                jtpMostraMensagens.add(servidor.getTodasMensagens(), this);
            } catch (RemoteException ex) {
                Logger.getLogger(jfTalkChat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jbEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfTalkChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfTalkChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfTalkChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfTalkChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfTalkChat().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListaUsuariosOnline;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAtualizaListaDeUsuariosOn;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JButton jbVoltaTelaInicial;
    private javax.swing.JLabel jlNomeDestinatario;
    private javax.swing.JLabel jlTalkChat;
    private javax.swing.JPanel jpTalkChat;
    private javax.swing.JTextField jtCaixaDeTexto;
    private javax.swing.JTextPane jtpMostraMensagens;
    // End of variables declaration//GEN-END:variables

    public String getCaixaDeTexto() {
        String caixaDeTexto = jtCaixaDeTexto.getText();
        return caixaDeTexto;
    }

}
